/// Automatically generated by BuildVersionEditorUpdate - DO NOT EDIT
public static class BuildVersion {
  public static readonly string VERSION = "1.11.3";
  public static readonly int BUILD = 510;
  public static readonly string PLATFORM = "Standalone";
}
