public class piRobotConstants
{
	public enum PIComponentId : uint {
		COMPONENT_UNKNOWN = 0,
		COMPONENT_POWER,
		COMPONENT_EYE_RING = 100,
		COMPONENT_RGB_EYE,
		COMPONENT_RGB_LEFT_EAR,
		COMPONENT_RGB_RIGHT_EAR,
		COMPONENT_RGB_CHEST,
		COMPONENT_LED_TAIL,
		COMPONENT_LED_BUTTON_MAIN,
		COMPONENT_BUTTON_MAIN = 200,
		COMPONENT_BUTTON_1,
		COMPONENT_BUTTON_2,
		COMPONENT_BUTTON_3,
		COMPONENT_MOTOR_LEFT_WHEEL = 300,
		COMPONENT_MOTOR_RIGHT_WHEEL,
		COMPONENT_MOTOR_HEAD_TILT,
		COMPONENT_MOTOR_HEAD_PAN,
		COMPONENT_ACCELEROMETER = 400,
		COMPONENT_GYROSCOPE,
		COMPONENT_DISTANCE_SENSOR_FRONT_LEFT = 500,
		COMPONENT_DISTANCE_SENSOR_FRONT_RIGHT,
		COMPONENT_DISTANCE_SENSOR_TAIL,
		COMPONENT_SPEAKER = 600,
		COMPONENT_SOUND_SENSOR,
		COMPONENT_ROBOT_PEER_SENSOR = 700,
	}
	
	public enum PIEyeAnimationIndex : int {
		EYEANIM_NONE = 0,
		EYEANIM_HALF_BLINK,
		EYEANIM_FULL_BLINK,
		EYEANIM_GRAVITY_EYE,
		EYEANIM_CIRCLE,
		EYEANIM_FAST_BLINK,
		
		EYEANIM_BITMAP = 0xffff,
	};
	
	
	// TODO - get this from the underlying API.
	public const int numEyeLights = 16;
	
}
